<a href="https://colab.research.google.com/github/Abeeraiftikhar/AI_and_Drug_Discovery_Course_2026/blob/main/Assignment_3_part2_QSAR_Pubchem_Fingerprint_Calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 3: Descriptor Calculation**

PaDELPy is a Python wrapper for the PaDEL-Descriptor (molecular descriptor calculation) software.  

It provide the following descriptors/fingerprint:  
* 1444 - 2D Descriptors
* 431 - 3D Descriptors
* 881 bits - PubChem Fingerprints

## **Install PaDELpy**

In [ ]:
!pip install padelpy

## **Import libraries**

In [2]:
import pandas as pd
import numpy as np
from google.colab import files
from padelpy import padeldescriptor

## **Load dataset**

In [3]:
df = pd.read_csv('df_lipinski.csv')
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL340270,inactive,4.931814,Brc1cccc[n+]1-c1ccc2cc(-[n+]3ccccc3Br)ccc2c1,442.154,4.91820,0.0,0.0
1,CHEMBL6063904,active,7.677781,C#CC1CCN(C2CC=C(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC...,841.003,8.73030,3.0,10.0
2,CHEMBL5182395,active,7.187087,C#CCCOC(=O)Nc1ccc(C2=NN(C(=O)c3ccc(Br)cc3)C(c3...,516.395,6.01240,1.0,4.0
3,CHEMBL5820135,active,8.346787,C#Cc1ccc(OC(=O)N2CCc3cc(-c4cc(C(=O)N(C)c5ccc(O...,777.922,6.42042,1.0,7.0
4,CHEMBL5843645,active,7.045757,C#Cc1cccc(C2CCCN2C2CC=C(c3ccc(C(=O)NS(=O)(=O)c...,800.938,7.97490,3.0,10.0

In [4]:
data = df[['canonical_smiles', 'molecule_chembl_id']]
data.head()

                                    canonical_smiles molecule_chembl_id
0       Brc1cccc[n+]1-c1ccc2cc(-[n+]3ccccc3Br)ccc2c1       CHEMBL340270
1  C#CC1CCN(C2CC=C(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC...      CHEMBL6063904
2  C#CCCOC(=O)Nc1ccc(C2=NN(C(=O)c3ccc(Br)cc3)C(c3...      CHEMBL5182395
3  C#Cc1ccc(OC(=O)N2CCc3cc(-c4cc(C(=O)N(C)c5ccc(O...      CHEMBL5820135
4  C#Cc1cccc(C2CCCN2C2CC=C(c3ccc(C(=O)NS(=O)(=O)c...      CHEMBL5843645

## **Convert to .smi format**

In [5]:
df_smi = data['canonical_smiles'].to_csv('smiles_chembl.smi', index=None, header=None)

In [6]:
! cat smiles_chembl.smi | head

Brc1cccc[n+]1-c1ccc2cc(-[n+]3ccccc3Br)ccc2c1
C#CC1CCN(C2CC=C(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)C1c1ccccc1C1CC1
C#CCCOC(=O)Nc1ccc(C2=NN(C(=O)c3ccc(Br)cc3)C(c3ccccc3)C2)cc1
C#Cc1ccc(OC(=O)N2CCc3cc(-c4cc(C(=O)N(C)c5ccc(O)cc5)c(C)n4C)c(C(=O)N4Cc5ccccc5C[C@H]4CN4CCOCC4)cc3C2)cc1
C#Cc1cccc(C2CCCN2C2CC=C(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)c(Oc4cnc5[nH]ccc5c4)c3)CC2)c1
C/C(=N\Nc1nc2ccccc2s1)c1ccc(-c2cccc(C(=O)O)c2)o1
C/C(=N\Nc1nc2ccccc2s1)c1ccc(-c2cccc(C(=O)O)n2)s1
C/C(=N\Nc1nc2ccccc2s1)c1cccc(-c2cccc(C(=O)O)n2)c1
C=C(C)c1ccccc1C1CCCN1C1CC=C(c2ccc(C(=O)NS(=O)(=O)c3ccc(NCC4CCOCC4)c([N+](=O)[O-])c3)c(Oc3cnc4[nH]ccc4c3)c2)CC1
C=C(C)c1ccccc1C1CCCN1C1CCC(c2ccc(C(=O)NS(=O)(=O)c3ccc(NCC4CCOCC4)c([N+](=O)[O-])c3)c(Oc3cnc4[nH]ccc4c3)c2)CC1

## **Calculate molecular Pubchem Fingerprints using "padeldescriptor" function**

In [ ]:
padeldescriptor(mol_dir= "smiles_chembl.smi",
                d_file='pubchem_fingerprints.csv',
                fingerprints = True,
                retainorder= True,
                #removesalt = True, standardizetautomers = True, standardizenitro=True
                )

In [7]:
!ls -lh pubchem_fingerprints.csv

-rw-r--r-- 1 root root 3.5M Feb 28 18:38 pubchem_fingerprints.csv

In [8]:
df_fingerprint = pd.read_csv("pubchem_fingerprints.csv")
df_fingerprint.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_chembl_1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_chembl_2,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_chembl_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_chembl_4,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_chembl_5,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Prepare Dataset for ML**

In [9]:
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL340270,inactive,4.931814,Brc1cccc[n+]1-c1ccc2cc(-[n+]3ccccc3Br)ccc2c1,442.154,4.91820,0.0,0.0
1,CHEMBL6063904,active,7.677781,C#CC1CCN(C2CC=C(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC...,841.003,8.73030,3.0,10.0
2,CHEMBL5182395,active,7.187087,C#CCCOC(=O)Nc1ccc(C2=NN(C(=O)c3ccc(Br)cc3)C(c3...,516.395,6.01240,1.0,4.0
3,CHEMBL5820135,active,8.346787,C#Cc1ccc(OC(=O)N2CCc3cc(-c4cc(C(=O)N(C)c5ccc(O...,777.922,6.42042,1.0,7.0
4,CHEMBL5843645,active,7.045757,C#Cc1cccc(C2CCCN2C2CC=C(c3ccc(C(=O)NS(=O)(=O)c...,800.938,7.97490,3.0,10.0

In [10]:
# Select only the columns we need for ML
meta_cols = df[['molecule_chembl_id', 'bioactivity_class', 'pIC50']]

# Reset index to ensure proper alignment
meta_cols = meta_cols.reset_index(drop=True)
df_fingerprint = df_fingerprint.reset_index(drop=True)

# Combine meta data with fingerprints
combined_df = pd.concat([meta_cols, df_fingerprint.drop(df_fingerprint.columns[0], axis=1)], axis=1)

# Inspect the first few rows
combined_df.head()

,molecule_chembl_id,bioactivity_class,pIC50,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL340270,inactive,4.931814,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL6063904,active,7.677781,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL5182395,active,7.187087,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL5820135,active,8.346787,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL5843645,active,7.045757,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Save and download the dataset**

In [11]:
# Save as CSV
combined_df.to_csv("QSAR_dataset.csv", index=False)
print("Combined dataset saved as QSAR_dataset.csv")

# Download file in Colab
files.download("QSAR_dataset.csv")

Combined dataset saved as QSAR_dataset.csv

# **Calculate other fingerprints**

## **Download xml Files from Github**

In [12]:
!wget https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip

--2026-02-28 18:39:51--  https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip [following]
--2026-02-28 18:39:51--  https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘padel_descriptors_xml.zip’

padel_descriptors_x 100%[===================>]  10.62K  --.-KB/s    in 0s

2026-02-28 18:39:51 (87.7 MB/s) - ‘padel_descriptors_xml.zip’ saved [10871/10871]

## **Unzip all files**

In [13]:
!unzip padel_descriptors_xml.zip

Archive:  padel_descriptors_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

## **Calculate Fingerprints**

In [14]:
# Specify the XML file for SubstructureFingerprinter directly
Substruc_fp = "SubstructureFingerprinter.xml"

# Calculate Substructure fingerprints
padeldescriptor(
    mol_dir='smiles_chembl.smi',
    d_file='Substructure_fingerprints.csv',
    fingerprints=True,
    descriptortypes= Substruc_fp,
    retainorder=True
    # removesalt=True, standardizetautomers=True
)